services:
  open-webui:
    build:
      context: .
      args:
        BUILDPLATFORM: 'linux/amd64'
      dockerfile: Dockerfile
    image: bmd1905/open-webui:${WEBUI_DOCKER_TAG:-latest}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT:-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}